<a href="https://colab.research.google.com/github/Mr-Stark-18/SOC2k21-Project/blob/Python-Course/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

In [ ]:
my_list = [1,2,3]

In [ ]:
import numpy as np

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
multi =[[1,2,3],[4,7,8],[9,7,6]]

In [ ]:
np.array(multi)

array([[1, 2, 3],
       [4, 7, 8],
       [9, 7, 6]])

In [ ]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
np.linspace(0,101,20)

array([  0.        ,   5.31578947,  10.63157895,  15.94736842,
        21.26315789,  26.57894737,  31.89473684,  37.21052632,
        42.52631579,  47.84210526,  53.15789474,  58.47368421,
        63.78947368,  69.10526316,  74.42105263,  79.73684211,
        85.05263158,  90.36842105,  95.68421053, 101.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5)

array([0.88746185, 0.75797289, 0.09943355, 0.45366156, 0.63330671])

In [ ]:
np.random.rand(5,5)

array([[0.89158953, 0.87557526, 0.72602347, 0.96783852, 0.03083206],
       [0.17816167, 0.08714076, 0.56667148, 0.29983498, 0.49039551],
       [0.0207463 , 0.58720893, 0.81974891, 0.47245425, 0.29368301],
       [0.93230771, 0.59099658, 0.90194975, 0.36612222, 0.81540793],
       [0.35075911, 0.38862622, 0.246677  , 0.15639555, 0.87756372]])

In [ ]:
np.random.randn(5,5)

array([[-1.23313472, -1.0838521 ,  3.01191456,  1.5512681 ,  0.99617227],
       [-0.20445809,  1.82638945,  2.65775604, -0.14623562,  0.66725059],
       [ 0.66191433, -1.17661111,  1.23882115, -0.81293094,  0.01391168],
       [ 1.58878697, -0.58055455,  1.18897289, -0.40075217,  0.51881844],
       [ 1.89853111,  0.73169813, -1.47138792,  0.39597334,  0.28941987]])

In [ ]:
np.random.randint(0,100,50)

array([32, 72, 18, 10, 21, 10, 90, 60,  7, 61, 76, 67, 52, 21, 60, 77, 60,
       96, 35, 49, 64, 36, 31, 21, 24, 90, 53, 95, 96, 13, 83, 28, 91,  3,
       90, 10,  8, 64, 42, 40, 31, 73, 46, 62, 25,  9, 54, 63, 82, 52])

In [ ]:
arr= np.arange(25)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr= np.random.randint(0,50,20)

In [ ]:
ranarr

array([25, 31, 26, 40, 35, 43, 16, 10, 16, 17,  2, 35, 40,  8, 20,  5,  7,
       29, 44, 42])

In [ ]:
ranarr.argmax()


18

In [ ]:
ranarr.argmin()

10

In [ ]:
arr.shape

(25,)

In [ ]:
arr=arr.reshape(5,5)

In [ ]:
arr.shape

(5, 5)

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
arr= np.arange(0,21)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
arr[8]

8

In [ ]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr[11:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
slice_of_arr = arr[0:10]

In [ ]:
slice_of_arr[:]=99

In [ ]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

this shows that data does not get copied but only referenced

In [ ]:
arr1 = arr.copy()

In [ ]:
arr1[:]=78

In [ ]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
arr_2d = np.array([[3,4,5],[5,6,7],[8,9,4]])

In [ ]:
arr_2d

array([[3, 4, 5],
       [5, 6, 7],
       [8, 9, 4]])

In [ ]:
arr_2d[2][1]

9

In [ ]:
arr_2d[2]

array([8, 9, 4])

In [ ]:
arr_2d[1,2]

7

In [ ]:
arr_2d[1:,:2]

array([[5, 6],
       [8, 9]])

In [ ]:
arr = np.arange(0,21)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
bool_arr=arr>5

In [ ]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

only the values where the oolean array was true are returned

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[arr<3]

array([0, 1, 2])

In [ ]:
arr_3d = np.arange(1,101).reshape((5,5,4))

In [ ]:
arr_3d

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [ ]:
arr_3d[:3,2:,:3]

array([[[ 9, 10, 11],
        [13, 14, 15],
        [17, 18, 19]],

       [[29, 30, 31],
        [33, 34, 35],
        [37, 38, 39]],

       [[49, 50, 51],
        [53, 54, 55],
        [57, 58, 59]]])

In [ ]:
arr_3d[4,3:,2:]

array([[ 95,  96],
       [ 99, 100]])

#NumPy operations
- Array with array
- array wiht scalars
- Univerrsal Array functions

In [ ]:
arr= np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr + 25

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [ ]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.max(arr)

10

In [ ]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])